### ISSUE TITLE
export Data file to be loaded in idraw

### ISSUE THREAD

**Issue by no-1ne** [idrawjs/studio#37]
Hello idraw team, Thank you for the library, currently looks like only image export is possible . How to export the data such that we can download it and load it in a idraw instance. 

Thanks in Advance

**Comment by chenshenhai** [comment]
`@idraw/studio` currently does not expose an API for outputting data. 

I'm thinking that I can listen to data changes through `props.onChange`

**Comment by chenshenhai** [comment]
I will add props.onChange in the next version to monitor the data changes of the idraw instance. 

Like this:

```tsx
<Studio 
  onChange={ (changedData)  => {
    // .....
  }
/>
```

**Comment by chenshenhai** [comment]
https://github.com/idrawjs/studio/pull/38  I have expose `props.onChange` to listen and export changed data of iDraw.js instance
