### ISSUE TITLE
Best way to create a table

### ISSUE THREAD

**Issue by Viktor-Lepekha** [idrawjs/studio#61]
If I were to create a table using idraw, would it be better to use html component or create a set of text components? Thank you for suggestions.

**Comment by chenshenhai** [comment]
@Viktor-Lepekha Of course! At present, it is the easiest way to draw the table by using the iDraw element of html type.

Currently, iDraw doesn't provide the element         for drawing tables directly. But you can use iDraw's html element type to draw tables indirectly.
