### ISSUE TITLE
Saving and Importing a JSON with pictures.

### ISSUE THREAD

**Issue by Peterksharma** [idrawjs/studio#63]
When you add a picture to a file and download the json the image is being saved as a base64 in the file. When I import the saved json back into the application the image file in there but it is not visible. 
<img width="1271" alt="Screenshot 2024-01-30 at 7 48 26 AM" src="https://github.com/idrawjs/studio/assets/120028593/faaa058e-84a6-4745-85b6-69c6494f1175">

**Comment by chenshenhai** [comment]
@Peterksharma Thanks for your feedback, I will check the issue later.

**Comment by chenshenhai** [comment]
I have fixed this issue in `idraw@0.4.0-beta.11`
