### ISSUE TITLE
是否可以增加一个按根节点页面对应呈现的开关或选项呢？

### ISSUE THREAD

**Issue by xeoshow** [idrawjs/studio#72]
试用studio，现在是下面布局方式，所有左边页面如Home、Sign Up、Sign In等等，都是在一个大页面里聚合显示。因为东西太多，其实都看不太清。要看清楚和真实操作，其实就会放大，本质上就是只显示当前操作的这一个页面。
所以希望可以有个开关，开启时（也许默认可以是开启），点击左侧根节点，右边画布仅展示该对应的页面，感觉操作会便利不少。
![image](https://github.com/idrawjs/studio/assets/1164284/2d279f1d-f487-47e9-aa2e-fe85d8865937)

**Comment by xeoshow** [comment]
网上看了几个类似产品，大部分是一个页面对应一个呈现，比如：
https://nihaojob.github.io/vue-fabric-editor/#/
https://salgum1114.github.io/react-design-editor/

**Comment by chenshenhai** [comment]
@xeoshow  `@idraw/studio`的左侧图层菜单里，有一个按钮可以单独进入`group`层进行独立编辑。 
你可以考虑先用这个功能实现独立页面的编辑功能
![image](https://github.com/idrawjs/studio/assets/8216630/efc0970c-8ba8-463b-9906-0ff9133b1cfd)
